---
title: "October 6 2016"
author: "Erin Feichtinger"
date: "October 5, 2016"
output: pdf_document
---

# Hatch Year Bird Survival Analyses 

## Pooled KM estimates and for cohorts 1981-2015

  The pooled estimate for survival of hatch year birds from fledge date to 1 year old over the entire 34 year period 1981-2015 reveals that the proportion of survivors 1 year post fledge is 0.46. The Cox models with cohort year as a predictor revealed that there is a lot of year to year variation in survival of hatch year birds. So, I estimated p at one year old (proportion still alive) for each cohort.  

  As expected, the proportion of survivors at one year old varies from year to year. The range is 0.24 to 1.00. However, another interesting thing to note is that the number of fledglings produced is variable across the years. Throughout the 80's, most of the fledglings produced made it to 1 year. However, there were few fledglings overall. Throughout time approaching 2015, the proportional survival is lower than the 80's and 90's but throuh 2000 - 2012 there were years with a large number of fledglings produced. 
  
```{r, echo=FALSE}
library(survival)
library(ggplot2)
library(car)
library(coxme)
library(kinship2)
library(SurvRegCensCov)
library(parfm)
library(plyr)
library(grid)
library(gridExtra)

bird.df <- read.csv("Erin_June_All_BirdsMass.csv")
bird.df<- bird.df[!duplicated(bird.df),]
bird.df <- bird.df[!is.na(bird.df$HatchNum),]
colnames(bird.df)[8] <- "Days"
bird.df["Yrs"] <- bird.df$Days/365.25
bird.df$FldgDate <- as.Date(bird.df$FldgDate, format = "%m/%d/%Y")
bird.df$LastObsDate <- as.Date(bird.df$LastObsDate, format = "%m/%d/%Y")
bird.df["Censor"] <- 1
bird.df$Censor[which(bird.df$Yrs >= 1)]<-0
year <- as.POSIXlt(bird.df$FldgDate)$year+1900
bird.df["Cohort"] <- year
bird.df$Cohort <- as.factor(bird.df$Cohort)
yrlg.df <- subset(bird.df, bird.df$Yrs > 0 & bird.df$Days > 0)
yrlg.df$Censor[which(yrlg.df$LastObsDate == "2016-04-12")] <- 0
yrlg.df$FldgDate <- as.numeric(yrlg.df$FldgDate)
yrlg.df$LastObsDate <- as.numeric(yrlg.df$LastObsDate)
yrlg.ob <- Surv(yrlg.df$Yrs, yrlg.df$Censor, type = c('right'))
my.fit <- survfit(yrlg.ob~1, conf.type = "log-log")
fit.yr <- survfit(yrlg.ob ~ yrlg.df$Cohort)
deaths <- c(2,5,1,7,2,2,0,9,90,4,59,3,12,7,10,6,4,2,55,
            38,33,59,28,67,60,74,30,98,39,91,122,15,47,72,49)
inds <- fit.yr$n
inds <- cbind(inds)
deaths <- cbind(deaths)
life.table <- data.frame(inds, deaths)
colnames(life.table) <- c("Inds", "Deaths")
life.table$Deaths <- as.numeric(life.table$Deaths)
life.table$Inds <- as.numeric(life.table$Inds)

life.table["p"] <- 1-(life.table$Deaths/life.table$Inds)
life.table$p <- round(life.table$p, 2)
life.table["Cohort"] <- c(1981,1982,1983,1984,1985,1986,1987,1988,1989,
                  1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,
                  2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,
                  2010,2011,2012,2013,2014,2015)
life.table$Cohort <- as.factor(life.table$Cohort)
p1 <- ggplot(life.table, aes(x=Cohort, y=p)) +
 geom_bar(stat="identity", fill="black") +
  theme(axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(x = "Cohort", y = "Proportion of Survivors")

p2 <- ggplot(life.table, aes(x=Cohort, y=Inds))+ 
  geom_bar(stat="identity", fill="gray47") +
  theme(axis.text.x=element_text(angle=300,hjust=1, vjust=0.5, size=12)) +
  labs(x = "Cohort", y= "Number of Fledglings Produced")

grid.arrange(p1, p2)
m.cumuls <- mean(life.table$p)
var.cumuls <- var(life.table$p)
sd.cumuls <- sd(life.table$p)
surv.stats <- cbind(m.cumuls,var.cumuls, sd.cumuls)
colnames(surv.stats) <- c("Mean","Variance","Standard Deviation")
surv.stats[,1:3] <- round(surv.stats[,1:3], 3)
# Mean, variance and standard deviation in proportion of survivals at 1 yr
surv.stats
# Range of proportional remaining alive at 1 yr 
range(life.table$p)

```

